# PlatformIO pre-script: optional build-time WiFi defaults and an OTA size guard.
import configparser
import gzip
import os

Import("env")  # noqa: F821 (provided by PlatformIO/SCons)

# ---- Optional WiFi defaults from the gitignored secrets.ini (see secrets.example.ini).
# Written to a generated header with every non-alphanumeric byte octal-escaped, so any
# SSID/password characters survive (command-line -D quoting does not handle backslashes).
def c_string(value):
    return '"' + "".join(chr(b) if b < 0x80 and chr(b).isalnum() else "\\%03o" % b
                         for b in value.encode("utf-8")) + '"'


secrets = os.path.join(env.subst("$PROJECT_DIR"), "secrets.ini")
generated = os.path.join(env.subst("$BUILD_DIR"), "generated")
os.makedirs(generated, exist_ok=True)
lines = ["#pragma once", "// Generated by scripts/build_options.py. Do not edit."]
# SMARTCLOCK_RELEASE=1 (scripts/make_release.py) ignores secrets.ini entirely.
if os.path.isfile(secrets) and os.environ.get("SMARTCLOCK_RELEASE") != "1":
    parser = configparser.ConfigParser(interpolation=None)
    parser.read(secrets, encoding="utf-8")
    ssid = parser.get("wifi", "ssid", fallback="").strip()
    if ssid:
        password = parser.get("wifi", "password", fallback="")
        lines += ["#define DEFAULT_WIFI_SSID " + c_string(ssid),
                  "#define DEFAULT_WIFI_PASS " + c_string(password)]
        print("build_options: default WiFi '%s' from secrets.ini" % ssid)
def write_if_changed(path, content):   # unchanged headers keep their timestamps
    if not os.path.isfile(path) or open(path, encoding="utf-8").read() != content:
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)


write_if_changed(os.path.join(generated, "wifi_secrets.h"), "\n".join(lines) + "\n")

# ---- Settings page: web/index.html, gzipped into PROGMEM. The page is self-contained
# (no external fonts or scripts) because it must work on the offline setup AP.
page = os.path.join(env.subst("$PROJECT_DIR"), "web", "index.html")
with open(page, "rb") as f:
    html = f.read()
packed = gzip.compress(html, compresslevel=9, mtime=0)   # mtime=0: reproducible
rows = [", ".join("0x%02x" % b for b in packed[i:i + 20]) for i in range(0, len(packed), 20)]
write_if_changed(os.path.join(generated, "web_index.h"), "\n".join([
    "#pragma once",
    "// Generated by scripts/build_options.py from web/index.html. Do not edit.",
    "#include <Arduino.h>",
    "static const size_t INDEX_HTML_GZ_LEN = %d;" % len(packed),
    "static const uint8_t INDEX_HTML_GZ[] PROGMEM = {",
    ",\n".join("  " + r for r in rows),
    "};", ""]))
print("build_options: web/index.html %d bytes -> %d gzipped" % (len(html), len(packed)))
env.Append(CPPPATH=[generated])

# ---- Size guard. The stock layout (4m3m, matched by platformio.ini) leaves 1 MB for the
# running sketch plus the staged OTA copy, so an image must fit twice, sector-rounded,
# with the updater's one-sector margin. 0x7e000 keeps a sector of slack below that.
# The first flash through the stock updater allows ~0x87000 (1 MB - stock's 0x78000).
MAX_IMAGE = 0x7E000


def check_size(target, source, env):
    path = target[0].get_abspath()
    size = os.path.getsize(path)
    print("build_options: firmware.bin %d bytes (limit %d, %.0f%% used)"
          % (size, MAX_IMAGE, 100.0 * size / MAX_IMAGE))
    if size > MAX_IMAGE:
        os.remove(path)  # never leave an image on disk that cannot be updated again
        print("ERROR: image exceeds the OTA limit; it could not be replaced over the air")
        return 1
    return 0


env.AddPostAction("$BUILD_DIR/${PROGNAME}.bin", check_size)
